### PR TITLE
Remove outdated partial Unified Runtime adapter

### PR DESCRIPTION
**Pull request by kbenzie**
The recommended integration into oneAPI through the construction kit is via the OpenCL adapter. This patch removes the outdated, partial, implementation of the Unified Runtime specification on top of ComputeMux.

### CODE REVIEW

**Review by coldav — APPROVED** [review]

**Comment by hvdijk** [comment]
No issue with this, but note that we need to make sure we remove this from our CI testing before we remove the code.

**Comment by kbenzie** [comment]
> No issue with this, but note that we need to make sure we remove this from our CI testing before we remove the code.

Is that in GitHub Actions?

**Comment by coldav** [comment]
> > No issue with this, but note that we need to make sure we remove this from our CI testing before we remove the code.
> 
> Is that in GitHub Actions?

sadly not but I will merge this once it's removed there if that is okay.

**Comment by kbenzie** [comment]
> sadly not but I will merge this once it's removed there if that is okay.

No worries, was just wondering if I need to do something in this PR.

**Pull request merged**
